server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:feedbackdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

slack:
  bot:
    token:
  signing:
    secret:
scheduled:
  user-id:
